services:
  backend:
    build:
      context: ./backend
    container_name: bolao-backend
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: bolao-frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped
